import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ImageContainer from "./components/ImageContainer";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="min-h-screen bg-main-home pb-5">
          <Navbar />
          <div className="pt-16">
            <div className="py-12 text-2xl font-bold px-5 text-blue-title md:text-3xl">
              <p>Pilih games yang</p>
              <p>kamu inginkan</p>
            </div>
            <div className="px-5 font-semibold text-white my-5 md:text-xl">
              <p>Games Individual</p>
            </div>
            <div className="grid grid-cols-2 gap-5 md:justify-items-start md:grid-cols-4 mx-5 lg:gap-0 lg:gap-y-5 lg:grid-cols-6 justify-items-center">
              <ImageContainer />
              <ImageContainer />
              <ImageContainer />
              <ImageContainer />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
